# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm_notes',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/llm_notes',
                'lib_path': 'llm_notes'},
  'syms': {'llm_notes.core': {'llm_notes.core.foo': ('core.html#foo', 'llm_notes/core.py')}}}
